server:
  port: 6062

spring:
  application:
    name: receipt-service

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/receipt-service-db
    username: receipt-service-user
    password: receipt-service-password
  jpa:
    show-sql: true

  flyway:
    locations: classpath:db/migration

management:
  endpoints:
    web:
      base-path: "/api/management"
      exposure:
        include: "health,info"